# Generated by Django 3.2.16 on 2022-10-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='login_require',
        ),
    ]
